name: MSBuild

on: [push, pull_request]

jobs:
 msbuild:
  runs-on: windows-latest

  strategy:
   matrix:
    configuration: [Release, ReleaseAVX2, ReleaseFreetype, ReleaseFreetypeAVX2]
    platform: [x64]

  steps:
  - uses: actions/checkout@v4
    with:
      submodules: recursive

  - name: Add MSBuild to PATH
    uses: microsoft/setup-msbuild@v2

  - name: Cache vcpkg
    uses: actions/cache@v4
    with:
      path: C:\vcpkg
      key: ${{ runner.os }}-vcpkg-${{ hashFiles('**/vcpkg.json') }}
      restore-keys: |
        ${{ runner.os }}-vcpkg-

  - name: Setup vcpkg
    run: |
      if (!(Test-Path "C:\vcpkg")) {
        git clone https://github.com/Microsoft/vcpkg.git C:\vcpkg
        C:\vcpkg\bootstrap-vcpkg.bat
      }
      C:\vcpkg\vcpkg integrate install
    shell: powershell

  - name: Install vcpkg dependencies
    run: |
      C:\vcpkg\vcpkg install cpr:x64-windows-static-md
      C:\vcpkg\vcpkg install nlohmann-json:x64-windows-static-md
      C:\vcpkg\vcpkg install cpr:x64-windows
      C:\vcpkg\vcpkg install nlohmann-json:x64-windows

  - name: Restore NuGet packages
    working-directory: ${{ github.workspace }}
    run: nuget restore Amalgam.sln

  - name: Build
    working-directory: ${{ github.workspace }}
    run: msbuild Amalgam.sln /p:Platform=${{ matrix.platform }} /p:Configuration=${{ matrix.configuration }}

  - uses: actions/upload-artifact@v4
    with:
     name: Amalgam${{ matrix.platform }}${{ matrix.configuration }}
     path: |
       output/${{ matrix.platform }}/${{ matrix.configuration }}/*.dll
       output/${{ matrix.platform }}/${{ matrix.configuration }}/*.exe

  - uses: actions/upload-artifact@v4
    with:
     name: Amalgam${{ matrix.platform }}${{ matrix.configuration }}PDB
     path: output/${{ matrix.platform }}/${{ matrix.configuration }}/*.pdb