name: MSBuild

on: [push, pull_request]

jobs:
 msbuild:
  runs-on: windows-latest

  strategy:
   matrix:
    configuration: [Release, ReleaseAVX2, ReleaseFreetype, ReleaseFreetypeAVX2]
    platform: [x64]

  steps:
  - uses: actions/checkout@v4
    with:
      submodules: recursive

  - name: Add MSBuild to PATH
    uses: microsoft/setup-msbuild@v2

  - name: Setup vcpkg
    uses: microsoft/setup-vcpkg@v1

  - name: Install vcpkg dependencies
    run: |
      vcpkg install cpr:x64-windows-static-md
      vcpkg install nlohmann-json:x64-windows-static-md

  - name: Restore NuGet packages
    working-directory: ${{ github.workspace }}
    run: nuget restore Amalgam.sln

  - name: Build
    working-directory: ${{ github.workspace }}
    run: msbuild Amalgam.sln /p:Platform=${{ matrix.platform }} /p:Configuration=${{ matrix.configuration }}

  - uses: actions/upload-artifact@v4
    with:
     name: Amalgam${{ matrix.platform }}${{ matrix.configuration }}
     path: output/${{ matrix.platform }}/${{ matrix.configuration }}/*.dll

  - uses: actions/upload-artifact@v4
    with:
     name: Amalgam${{ matrix.platform }}${{ matrix.configuration }}PDB
     path: output/${{ matrix.platform }}/${{ matrix.configuration }}/*.pdb